services:
  calamity-server:
    container_name: calamity-server
    build:
      context: .
      args:
        UID: 1000
        GID: 1000
    tty: true
    stdin_open: true
    ports:
      - "7777:7777"
    volumes:
      - ./tModLoader:/home/tml/.local/share/Terraria/tModLoader
    environment:
      - WORLD=/home/tml/.local/share/Terraria/tModLoader/Worlds/adriangei.wld
      - AUTOCREATE=0
      - PASSWORD=
      - MOTD="Completamente loco y traicionado"
    restart: unless-stopped