services:
  calamity-server:
    container_name: calamity-server
    build:
      context: .
      args:
        UID: 1000
        GID: 1000
    tty: true
    stdin_open: true
    ports:
      - "7777:7777"
    volumes:
      - ./tModLoader:/home/tml/.local/share/Terraria/tModLoader
    environment:
      - WORLD=/home/tml/.local/share/Terraria/tModLoader/Worlds/adriangei.wld
      - PASSWORD=
      - MOTD="Completamente loco y traicionado"
      - AUTOCREATE=0
    restart: unless-stopped

  playit:
    image: ghcr.io/playit-cloud/playit-agent:0.17
    network_mode: host
    environment:
    - SECRET_KEY=21894f27ce00641f171cc30d9aa091c162e912b3d6ca42104c0feb7ed56a4db4
    restart: unless-stopped